import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "The Web Geeks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  >
    <div>
      <div className="bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900 min-h-screen">
        <div className="relative overflow-hidden">
          {/* <!-- Background elements without animations --> */}
          <div className="absolute inset-0 overflow-hidden">
            <div className="absolute -top-1/2 -left-1/4 w-full h-full bg-gradient-to-r from-purple-500/5 to-blue-500/5 rounded-full filter blur-3xl opacity-20"></div>
            <div className="absolute top-1/2 right-0 w-1/2 h-1/2 bg-gradient-to-l from-pink-500/10 to-cyan-500/10 rounded-full filter blur-3xl opacity-30"></div>
          </div>
          <Navbar />
          <div className="">{children}</div>
          <Footer />
        </div>
      </div>
    </div>
  </body>
</html>
  );
}
